baseURL: /
languageCode: en-us
paginate: 6
theme: portio-hugo-data-science
title: Plamen's Data Science Portfolio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Services
      url: '#service'
      weight: 3
    - name: Portfolio
      url: '#portfolio'
      weight: 4
    - name: Experience
      url: '#resume'
      weight: 5
    - name: Ebooks
      url: 'blog'
      weight: 6
  sitemap:
    - name: Home
      url: /
      weight: 1
    - name: eBooks
      url: blog
      weight: 2
params:
  blogPageURL: blog
  contactButtonLabel: Contact Plamen
  contactLink: '#contact'
  copyright: All right reserved copyright © Plamen Rabadzhiyski 2023
  footerLogo: images/site-navigation/PlamenLogo.png
  formspreeURL: https://formspree.io/f/xjvqrvbb
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/PlamenLogo.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/plamen-rabadzhiyski/
      weight: 1
    # - icon: fa-youtube-square
    #   url: https://www.youtube.com/
      # weight: 2
    - icon: fa-twitter-square
      url: https://twitter.com/p_rabadzhiyski
      weight: 3
