baseURL: /
languageCode: en-us
paginate: 6
theme: portio-hugo-data-science
title: Plamen Rabadzhiyski
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: About
      url: '#about'
      weight: 2
    - name: Services
      url: '#service'
      weight: 3
    - name: Portfolio
      url: '#portfolio'
      weight: 4
    - name: Experience
      url: '#resume'
      weight: 5
    #- name: Useful
     # url: 'blog'
      #weight: 6
    - name: Blog
      url: https://data-science-ai.com/blog/
      weight: 6
  sitemap: # change name in the 'footer.html'
    - name: Newsletter
      url: https://data-science-ai.kit.com/newsletter #/
      weight: 1
    - name: Blog
      url: https://data-science-ai.com/blog/
      weight: 2

params:
  blogPageURL: blog
  contactButtonLabel: Join My Newsletter
  contactLink: https://data-science-ai.kit.com/newsletter #'#contact'
  copyright: All rights reserved. Copyright © Plamen Rabadzhiyski, 2025.
  footerLogo: images/site-navigation/PlamenLogo.png
  formspreeURL: https://formspree.io/f/xjvqrvbb
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/PlamenLogo.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/plamen-rabadzhiyski/
      weight: 1
    # - icon: fa-youtube-square
    #   url: https://www.youtube.com/
      # weight: 2
    - icon: fa-twitter-square
      url: https://twitter.com/p_rabadzhiyski
      weight: 3
      
      
# <script async data-uid="d14c77e73e" src="https://data-science-ai.kit.com/d14c77e73e/index.js"></script>
